// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwufgowdaaduddgoqnnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dWZnb3dkYWFkdWRkZ29xbm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTYwOTcsImV4cCI6MjA3MDgzMjA5N30.sffYSEexXvW7edDUJj5m7aE09KX4Xl3w-oIs4uVIC1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});